project_id = "sfezlilyqbtusynakgwp"

[functions.send-quiz-results]
verify_jwt = false

[functions.enhance-text]
verify_jwt = false

[functions.generate-content-grid]
verify_jwt = false

[functions.copy-coach]
verify_jwt = false

[functions.notion-setup]
verify_jwt = false
